version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: hilmi-postgres-local
    environment:
      POSTGRES_USER: hilmiuser
      POSTGRES_PASSWORD: hilmi123
      POSTGRES_DB: hilmiweb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: